###############################################################################
# Define here application version if needed
###############################################################################

# image:
#   tag: 14.1.0-debian-10-r80

grafana:
  enabled: false

alertmanager:
  ingress:
      enabled: true
      #ingressClassName: nginx-internal
      ingressClassName: nginx
      annotations: 
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts: 
        - alert-manager.INSERT_VDOMAIN
      tls: 
        - hosts:
            - alert-manager.INSERT_VDOMAIN
          secretName: alertmgr-ingress-cert

prometheus:
  ingress:
    enabled: true
    #ingressClassName: nginx-internal
    ingressClassName: nginx
    annotations: 
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts: 
      - prometheus.INSERT_VDOMAIN
    tls: 
      - hosts:
          - prometheus.INSERT_VDOMAIN
        secretName: prometheus-ingress-cert
