steps:
- id: 'Provision Infra Components'
  name: 'gcr.io/$PROJECT_ID/privateedition'
  entrypoint: 'bash'
  args: ['services/provision-infra.sh']
  env:
    - 'VDOMAIN=${_VDOMAIN}'
    - 'VGCPPROJECT=${_VGCPPROJECT}'
    - 'VGCPREGION=${_VGCPREGION}'
    - 'VGKECLUSTER=${_VGKECLUSTER}'
    - 'VHELMCOMMAND=${_VHELMCOMMAND}'
  timeout: '7200s'
timeout: '7200s'