###############################################################################
# Additional IXN parameters
# https://all.docs.genesys.com/IXN/Current/IXNPEGuide/Configure
###############################################################################
tenant:
  id: "tenant_id"
  sid: "tenant_sid"

ixnService:
  image:
    ixnServer:
      repository: "ixn/interaction_server"
      tag: 100.0.006.1204
    logSidecar:
      enabled: true
      registry: "docker.io"
      repository: "fluent/fluent-bit"
      tag: "1.8.5"
    ixnNode:
      repository: "ixn/ixn_node"
      tag: 100.0.007.0002

  ixnServer:
    secrets:
      db:
        enabled: true
        secretName: "ixn-db-secret-tenant_sid"
        username: "${ixn_db_user}"
        password: "${ixn_db_password}"
    db:
      name: IXN_DB
      host: POSTGRES_ADDR
    dbinit:
      enabled: true
  
  ixnNode:
    secrets:
      db:
        enabled: true
        secretName: "ixn-node-db-secret-tenant_sid"
        username: "${ixn_db_user}"
        password: "${ixn_db_password}"
    db:
      name: IXN_NODE_DB
      host: POSTGRES_ADDR
    dbinit:
      enabled: true
    redis:
    - host: infra-redis-redis-cluster.infra.svc.cluster.local
      port: 6379
      is_redis_cluster: "true"

ixnVQNode:
  image:
    ixnVQNode:
      repository: "ixn/ixn_vq_node"
      tag: 100.0.007.0002

# Custom override-valuse for usage in pre-release-script
kafkaAddress: kafka-helm-cp-kafka.kafka.svc.cluster.local